### ISSUE TITLE
Error when converting dates

### ISSUE THREAD

**Issue by Timst** [Cretezy/fddp#1]
Got this when trying to convert:

**C:\Go\work\src\github.com\Cretezy\fddp>fddp.exe convert personal/messages.htm personal/messages.json
panic: parsing time "Friday, 1 February 2013 at 16:40 UTC+01" as "Monday, January 2, 2006 at 3:04pm MST": cannot parse "1 February 2013 at 16:40 UTC+01" as "January"**

goroutine 1 [running]:
main.check(0x9c7dc0, 0xc0692660a0)
        C:/Go/work/src/github.com/Cretezy/fddp/helpers.go:8 +0x51
main.FromHTML.func1.1(0x0, 0xc06926cd80)
        C:/Go/work/src/github.com/Cretezy/fddp/convert_html.go:59 +0x3e5
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc06926cd50, 0xc04202f580, 0x9fb220)
        C:/Go/work/src/github.com/PuerkitoBio/goquery/iteration.go:10 +0x11a
main.FromHTML.func1(0x0, 0xc06926cd20)
        C:/Go/work/src/github.com/Cretezy/fddp/convert_html.go:64 +0x227
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc06926ccf0, 0xc04202f700, 0x7)
        C:/Go/work/src/github.com/PuerkitoBio/goquery/iteration.go:10 +0x11a
main.FromHTML(0xc047c8a000, 0x5b8cefb, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/work/src/github.com/Cretezy/fddp/convert_html.go:66 +0x25d
main.ConvertAction(0xc042044640)
        C:/Go/work/src/github.com/Cretezy/fddp/convert.go:35 +0xca
github.com/codegangsta/cli.HandleAction(0x789fc0, 0x829d38, 0xc042044640, 0xc042038600, 0x0)
        C:/Go/work/src/github.com/codegangsta/cli/app.go:487 +0x83
github.com/codegangsta/cli.Command.Run(0x810d49, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x81f7b7, 0x22, 0x0, ...)
        C:/Go/work/src/github.com/codegangsta/cli/command.go:207 +0xb79
github.com/codegangsta/cli.(*App).Run(0xc042036b60, 0xc042042080, 0x4, 0x4, 0x0, 0x0)
        C:/Go/work/src/github.com/codegangsta/cli/app.go:250 +0x7d7
main.main()
        C:/Go/work/src/github.com/Cretezy/fddp/main.go:23 +0x134

**Comment by Cretezy** [comment]
Will fix. Facebook sometimes changes the date format.

**Comment by Cretezy** [comment]
Fixed in https://github.com/Cretezy/fddp/commit/fb0d559731b6368c4dd2e90e15e6f861f106e80f. Broke samples though.

**Comment by Cretezy** [comment]
Fixed samples in https://github.com/Cretezy/fddp/commit/c43c89d3a67fb3e00774867570a76022e6950a5d
